name: hand_e_kraft_app
description: Bluetooth control app for Hand-e-Kraft glove
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2 
